apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/leonidv/idel-backend:test
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1.0
              memory: 512Mi
          ports:
            - containerPort: 8080
          env:
            - name: jwt.frontend.url
              value: https://test.saedi.io

            - name: security.cors.allowed-origins
              value: https://test.saedi.io          
          envFrom:
            - secretRef:
                name: dbcredentials
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      name: backend-http