apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saedi-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - api.test.saedi.io
      secretName: tls-api.test.saedi.io
    - hosts:
        - test.saedi.io
      secretName: tls-test.saedi.io

  rules:
    - host: api.test.saedi.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  name: backend-http
    - host: test.saedi.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webui-service
                port:
                  name: webui-http

