FROM docker.io/bellsoft/liberica-openjdk-debian:18.0.1.1-2

ARG PROJECT_DIR
ARG SCRIPTS_DIR

ENV LOG_DIR=/idel/logs

COPY "$SCRIPTS_DIR/*" /app/
COPY "../../backend/build/libs/idel-backend.jar" /app/


ENTRYPOINT ["/app/run.sh"]