@startuml

!include theme.puml

actor User
User -> "groups" : GET onlyAvailable=true
activate "groups"
User <-- "groups" : list of groups
deactivate "groups"

User -> "joinrequests" : POST joiningKey
activate "joinrequests"



alt PUBLIC (user can join without approving)
    User <-- "joinrequests" : status=APPROVED
else CLOSED (admin should approve)
    User <-- "joinrequests" : status=UNRESOLVED
    actor Admin
    Admin ->  "joinrequests" : GET ?groupId={groupId}
    Admin <-- "joinrequests" : list of group's join requests
    Admin ->  "joinrequests" : PATCH /{joinrequestsId}/status APPROVED
    deactivate "joinrequests"
end

User ->  "ideas"  : GET /?groupId={groupId}
activate "ideas"
User <-- "ideas" : list of group's idea
deactivate "ideas"

@enduml

