@startuml


'actor User order 1
'participant groups order 2
'participant joinrequests order 3
'participant ideas order 4
'actor Admin order 5

skinparam monochrome true
skinparam shadowing false

skinparam Sequence {
    GroupBorderColor #ff0f0f
    GroupShadow false
    GroupBorderThickness 1
    GroupHeaderFontStyle normal
    GroupBodyBackgroundColor white
}


actor User
User -> "groups" : GET onlyAvailable=true
activate "groups"
User <-- "groups" : list of groups
deactivate "groups"

User -> "joinrequests" : POST joiningKey
activate "joinrequests"



alt PUBLIC (user can join without approving)
    User <-- "joinrequests" : status=APPROVED
else CLOSED (admin should approve)
    User <-- "joinrequests" : status=UNRESOLVED
    actor Admin
    Admin ->  "joinrequests" : GET ?groupId={groupId}
    Admin <-- "joinrequests" : list of group's join requests
    Admin ->  "joinrequests" : POST /{joinrequestsId}/status APPROVED
    deactivate "joinrequests"
end

User ->  "ideas"  : GET /?groupId={groupId}
activate "ideas"
User <-- "ideas" : list of group's idea
deactivate "ideas"

@enduml

