skinparam monochrome true
skinparam shadowing false

skinparam Sequence {
    GroupBorderColor #ff0f0f
    GroupShadow false
    GroupBorderThickness 1
    GroupHeaderFontStyle normal
    GroupBodyBackgroundColor white
}
