# enalbe some features for testing, like as basic authentication. See testing.md for more details.
# Don't use it in production, it's very dangerous!
testmode: false

security:
  httpbasic:
    realm: ideaelection
  cors:
    allowed-origins: https://saedi.zap-it.ru, http://saedi.zap-it.ru, https://api.zap-it.ru, http://api.zap-it.ru,

spring:
  application:
    name: saedi
  config:
    import: "optional:.dev.yaml"

  datasource:
    url: jdbc:postgresql://localhost:5432/saedi
    username: admin
    password: password

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 115577720302-jtm4mampbkbq62rerrb3thdcj5qq3egb.apps.googleusercontent.com
            client-secret: yLVkDuyUGMnM6J2iHtJ7t1a-

management:
  endpoints:
    web:
      base-path: /m
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled: true

jwt:
  private.key: classpath:jwt_private_key
  public.key: classpath:jwt_public_key.crt
  frontend.url: http://localhost:8080/users/me
  
server:
  forward-headers-strategy: framework
